fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    java:
      repo: https://github.com/puppetlabs/puppetlabs-java.git
    mysql:
      repo: https://github.com/puppetlabs/puppetlabs-mysql.git
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    yum:
      repo: https://github.com/voxpupuli/puppet-yum.git
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
    phantomjs:
      repo: https://github.com/treydock/puppet-module-phantomjs.git
  symlinks:
    inam: "#{source_dir}"
